baseURL = 'https://davidmn.org'
languageCode = 'en-gb'
title = 'davidmn.org'
theme = "beautifulhugo"
enableGitInfo = true

[Author]
  name = "Dave Megins-Nicholas"
  mastodon = "mastodon.social/@megaslippers"
  twitter = "MegaSlippers"
  github = "davidmn"
  instagram = "MegaSlippers"
  spotify = "metaslippers"

[Params]
  subtitle = "Just this guy, you know?"
  avatar = "avi.jpg"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  commit = "https://github.com/davidmn/davidmn.org/tree/"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1
[[menu.main]]
  name = "About"
  url = "/page/about"
  weight = 2
