baseURL = 'https://www.davidmn.org'
languageCode = 'en-gb'
title = 'davidmn.org'
theme = "beautifulhugo"

[author]
    name = "Dave Megins-Nicholas"
    mastodon = "@megaslippers@mastodon.org.uk"
    twitter = "MegaSlippers"
    github = "davidmn"
    instagram = "MegaSlippers"
    spotify = "metaslippers"

[Params]
  subtitle = "Mostly boardgames"
  avatar = "avi.jpg"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1
