baseURL = 'https://davidmn.org'
languageCode = 'en-gb'
title = 'davidmn.org'
theme = "beautifulhugo"
enableGitInfo = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
  homeTitle = "Just this guy, you know?"
  logo = "avi.jpg"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  commit = "https://github.com/davidmn/davidmn.org/tree/"
  readingTime = true
  useHLJS = true

[params.author]
  name = "Dave Megins-Nicholas"
  mastodon = "mastodon.social/@megaslippers"
  github = "davidmn"
  spotify = "metaslippers"
  bluesky = "megaslippers.net"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1
[[menu.main]]
  name = "About"
  url = "/page/about"
  weight = 2
